/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Material 3 — Anvaya palette (from Stitch design tokens)
        "on-error-container": "#93000a",
        "surface-variant": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-container": "#a5a6a2",
        secondary: "#006d3e",
        "on-primary-container": "#85b098",
        "on-background": "#131b2e",
        "inverse-primary": "#a4d0b8",
        "on-surface": "#131b2e",
        "primary-fixed": "#c0edd3",
        background: "#faf8ff",
        "primary-container": "#1a4331",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        primary: "#002d1c",
        "on-secondary-fixed": "#00210f",
        "on-primary-fixed-variant": "#264e3c",
        "surface-container": "#eaedff",
        "error-container": "#ffdad6",
        "outline-variant": "#c1c8c2",
        "inverse-surface": "#283044",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#454744",
        "secondary-container": "#8cf5b2",
        "on-tertiary-fixed": "#1a1c19",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        tertiary: "#242623",
        "surface-tint": "#3e6752",
        "tertiary-fixed": "#e3e3de",
        "on-surface-variant": "#414944",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#a4d0b8",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "on-primary-fixed": "#002114",
        "surface-bright": "#faf8ff",
        "secondary-fixed-dim": "#73db9a",
        "on-secondary-container": "#007241",
        "surface-container-low": "#f2f3ff",
        surface: "#faf8ff",
        "on-secondary-fixed-variant": "#00522d",
        outline: "#717973",
        "tertiary-container": "#3a3c39",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#c6c7c2",
        "secondary-fixed": "#8ff8b4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        xl: "32px",
        md: "16px",
        "margin-mobile": "16px",
        base: "4px",
        gutter: "16px",
        xs: "4px",
        sm: "8px",
        lg: "24px",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
      },
      fontSize: {
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(0,0,0,0.04)",
        "glass-lg": "0 8px 32px 0 rgba(0,0,0,0.08)",
        "glass-xl": "0 12px 48px 0 rgba(0,0,0,0.12)",
        "top-nav": "0 8px 32px 0 rgba(0,0,0,0.08)",
        "glow-green": "0 0 20px rgba(0,109,62,0.15)",
        "glow-green-lg": "0 0 40px rgba(0,109,62,0.2)",
        "inner-glow": "inset 0 1px 2px rgba(255,255,255,0.3)",
        "card-hover": "0 16px 48px 0 rgba(0,0,0,0.1)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-scale": {
          "0%": { opacity: "0", transform: "scale(0.95) translateY(8px)" },
          "100%": { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(0,109,62,0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(0,109,62,0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "bounce-in": {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-down": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-x-in": {
          "0%": { transform: "scaleX(0)" },
          "100%": { transform: "scaleX(1)" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out",
        "fade-in-scale": "fade-in-scale 0.5s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slide-up 0.4s ease-out",
        "slide-in-right": "slide-in-right 0.4s ease-out",
        "slide-in-left": "slide-in-left 0.4s ease-out",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
        float: "float 3s ease-in-out infinite",
        "spin-slow": "spin-slow 8s linear infinite",
        "bounce-in": "bounce-in 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        "slide-down": "slide-down 0.3s ease-out",
        "scale-x-in": "scale-x-in 0.5s ease-out",
        "count-up": "count-up 0.5s ease-out",
      },
    },
  },
  plugins: [],
};
